LilithHafner/Chairmarks.jl

src/show.jl
Bugs introduced in 05492c9a3c4563cf80127e142f68355a5309294f
=> Try to fix CI by fixing some display bugs

.github/workflows/CI.yml, README.md
=> Don't limit CI concurrency

docs/src/index.md
Thanks to Sundar R on Zulip for pointing this out
=> Fix typo in doctest

Project.toml
=> Release 0.2.3

Project.toml
=> Release 0.3.1

Project.toml, docs/src/migration.md, ext/StatisticsChairmarksExt.jl, src/Chairmarks.jl, src/public.jl, src/show.jl, src/statistics.jl, src/types.jl, test/runtests.jl
- Make Sample and Benchmark public!
- Add Statistics package extension & publicise field wise operation
=> Make `Sample` and `Benchmark` public and add public package extension with Statistics

Project.toml
=> Release 1.0.0

Project.toml
One bugfix and lots of documentation improvements
=> Release 1.0.1

Project.toml
=> Release 1.0.2

Project.toml
Interpolation
DocumenterVitepress
=> Release 1.1.0

src/public.jl
=> docstrings typo

Project.toml
Add experimental gc=false option
=> Release 1.2.0

.github/workflows/CI.yml
Enabled by https://github.com/julia-actions/setup-julia/pull/234 and https://github.com/julia-actions/setup-julia/pull/202
=> Make CI tests track lts, min, and pre

docs/src/explanations.md
This prose comes in large part from https://github.com/LilithHafner/Chairmarks.jl/issues/100#issuecomment-2089047771
=> Add explanations for some deviations from BenchmarkTools

Project.toml
User-facing changes are minor display formatting improvements, a bugfix for `seconds=Inf`, several small docs improvements, and a bugfix for parsing standalone literal symbols.
=> Release 1.2.2

src/Chairmarks.jl
Example from docs has typo. Correcting.
=> Update doc typo in Chairmarks.jl

Project.toml, src/benchmarking.jl, src/macro_tools.jl, src/public.jl, src/show.jl, src/statistics.jl, test/runtests.jl
=> Support comparative benchmarking

src/benchmarking.jl, test/runtests.jl
=> Fix some bugs for early return cases when comparing and add tests

src/benchmarking.jl, test/runtests.jl
This is breaking but it breaks an unreleased feature (comparisons)
=> Share setup between samples of compared functions and add test

.github/workflows/CI.yml, codecov.yml, test/runtests.jl
=> Get codecov working reliably

src/macro_tools.jl, test/runtests.jl
=> Use shorter and more robust l-value and r-value tracking for underscore replacement
