LilithHafner/Chairmarks.jl

.github/workflows/CI.yml

That job is too slow (3x slower than Windows/Julia 1.0).
Still run CI on mac/linux and 1.6 and windows on 1.0, 1, and nightly

Don't run CI on Windows/Julia 1.6

---

README.md
docs/src/index.md

Add some docs beyond the docstrings

---

docs/src/index.md
src/public.jl

The doctests test as much as possible while still being entirely performance independent. Something could be doctested to take 1ns and end up taking 10s with compile time, gc time, etc and it would still pass doctests.
The one exception to this is changing number of samples below 5 when displaying a full `@be` result i.e. crossing between these sets (1, 2, 3, 4, 5:inf).
Excludes the README because they are copied directly from index.md & wouldn't actually run anyway.

Put back doctests

---

src/show.jl
src/types.jl
test/runtests.jl

The doctests don't adequately cover display testing because they filter out alot of important information to be insensitive to noise. These tests use static fabricated data to avoid that.
Revealed a bug in a `Sample` constructor that is only used to make `repr` output `eval`able

Add display tests and fix Sample constructor, display on old versions, and display of empty benchmarks

---

README.md
docs/src/index.md

This is a kind of shitty way to opt out, I'll expose a better one (e.g. `checksum=false`) if someone asks for it. This also delves into internals and makes them a wee bit public. I'll bump a breaking change if I make breaking changes to map or reduction after this.

Document checksum behavior and how to opt out

---

src/benchmarking.jl

When we decide to run a bench(10) as pre-calibration because the `bench(1)` call was too fast (less than .015% of total budget/0.3% of calibration budget), and then that calibration takes too long (e.g. 10% of total budget), use its results instead of replacing it with `bench(0)` (or any number <= 20). This can happen when `bench(1)` gives a result of `0` due to low timekeeping precision, and `bench(10)` gives a high result due to low total budged.
Fixes #24, an issue that occurs when the time budget is low compared to the clock resolution.
TODO: consider simplifying and/or refactoring calibration system. Esp considering the possibility of low precision clocks.

Better calibration result handling

---

docs/src/index.md
src/types.jl

It's a checksum because it contains no useful information about the returned values and is confined to a single Float64.

Rename `value` to `checksum`

---

README.md
docs/src/index.md
docs/src/migration.md
src/Chairmarks.jl

- shorter readme and more links to docs
- add docstring to module (for a shorter docstring than the default
Requires 0.3.1 to be registered and docs stable for links in README to not be broken.

Concision and crosslinking in docs

---

src/benchmarking.jl
test/runtests.jl

Fixes #56. In local tests, the new test failed 3/3 times without the patch.

Fix and test reporting undef results bug

---

docs/make.jl

DocumenterVitepress makes these clearly nest withing How to, so the dots are unnecessary.

remove ... from docs file names because they don't look nice in Vitepress and are no longer necessary

---

src/benchmarking.jl
test/runtests.jl

The test is always 10/10 locally, but I don't want false positives.

Test and fix issue 74 for Julia version 1.8+

---

src/benchmarking.jl
test/runtests.jl

Fixes #91. Bug introduced by #57. The extra sample comes from calibration:
https://github.com/LilithHafner/Chairmarks.jl/blob/5aa41f9d4df13120f5d1cfba2fc210e8f3fcafc8/src/benchmarking.jl#L91-L97
So we start populating at 2 in the main loop.

Fix off by one error in sample count

---

src/benchmarking.jl
test/runtests.jl

Respect evals even when samples=0

---

docs/src/tutorial.md
src/public.jl
src/show.jl
src/types.jl
test/runtests.jl

Consistent with `Vector` and `BenchmarkTools.Benchmark` both of which which uses one space for trailing lines.

Indent trailing lines of benchmark display by one space

---

docs/src/migration.md

If I'm not mistaken, the time conversion in the ["Fields"](https://chairmarks.lilithhafner.com/v1.2.1/migration#Fields) table has two typos.
```Julia-repl
julia> s = @b rand(100) sum
7.854 ns
julia> s.time # in seconds
7.853748680042239e-9
julia> s.time*1e9 # in nanoseconds
7.853748680042239
```

Fix time conversion in BenchmarkTools comparison

---

src/show.jl
test/runtests.jl

Includes tests and justification (alignment with Vector display).

make `show(::Benchmark)` indent samples 1 space instead of 2

---

src/benchmarking.jl
test/runtests.jl

Fixes #104 
- handle seconds=Inf gracefully
- handle very high seconds gracefully
- handle time_ns() being close to the top of its range and overflowing mid-benchmark gracefully (with no errors)
- add tests for all of the above

Handle seconds=Inf and very high seconds args gracefully (unbounded runtime if samples and evals are specified, otherwise throw)

---

test/runtests.jl

Instead of using the elapsed time to make sure the function is run only once, track the number of function evaluations with side effects. Also clarify a comment.

Make the "no warmup" test less flaky

---

bench/runbenchmarks.jl
src/benchmarking.jl
test/runtests.jl

This is necessary because the test fails every once in a while so we need to wrap it in RegressionTests.jl to avoid false positives. The downside is it could slide slowly.
See #74, #75

Make flaky Issue 74 test a regression test not an absolute test

---

src/benchmarking.jl

This PR is to let RegressionTests see if it's a performance improvement or not. IMO it's a slight readability improvement.

Replace recursion with mutation in the large/infinite seconds case

---

bench/runbenchmarks.jl
src/macro_tools.jl
test/runtests.jl

Fixes #99.
This special case assumes that all non-Expr objects in an expression tree evaluate to themselves. This is a false assumption in the case of `QuoteNode(::Symbol)`.
Additionally, this `Returns` gives the compiler slightly less information by inhibiting constant propagation of literals. Constant propagation of literals is usually bad (misleadingly low runtimes) in this case but this particular fix also results in `@b 2 rand` and `@b 1+1 rand` having different properties with the _latter_ more constprop-able. I was not able to find a case where the `Returns` is helpful.
Returns was added in 4f8a8c8bb0635b53a0162d3958a7c24430d7766d to avoid compilation time and paired with the test
```julia
@testset "no compilation" begin
res = @b @eval (@b 100 rand seconds=.001)
@test .001 < …
```

Macro Expansion: Special case QuoteNode by `Returns`ing the unpacked value rather than the QuoteNode itself.

---

docs/src/why.md

Update truthful section based on the use of `Base.donotdelete` and remove example of funky behavior because that behavior no longer reproduces.
Fixes #124

Update truthful section based on the use of `Base.donotdelete`

---

docs/src/migration.md
docs/src/reference.md
docs/src/tutorial.md
src/Chairmarks.jl
src/benchmarking.jl
src/public.jl
src/types.jl
test/runtests.jl

Implements and closes #71 by providing a global default mechanism: `Chairmarks.DEFAULTS.seconds = 1`.

Support `Chairmarks.DEFAULTS.seconds`

---

bench/runbenchmarks.jl
docs/src/migration.md
docs/src/why.md
src/benchmarking.jl
src/types.jl
test/runtests.jl

- **Remove checksum mechanics because Base.donotdelete is more appropriate since 1.8**
- **Update docs**
Technically breaking because the `checksum=false` kwarg now throws.
Folks can still use teardown.

Remove checksum plumbing and configurability

---

test/runtests.jl

- **full pipeline seconds=.001 (29.3=>22.9)**
- **skip Aqua's persistent_task tests (22.9s => 20.5s)**
- **assorted other changes (reducing runtime budgets) (20.5s => 18.3s)**

Make tests (excluding RegressionTests.jl) run 37% faster

---

src/benchmarking.jl
test/runtests.jl

- Allow calibration to request a number of evals up to and exceeding typemax(Int)
- round down to typemax(Int) instead of erroring 
- Add tests for long runtime
Factored out of #142 
Note that CI does not currently run on 32-bit

Fixups for 32-bit

---

.github/workflows/CI.yml
src/benchmarking.jl
test/runtests.jl

Overhaul CI strategy

---

src/benchmarking.jl
test/runtests.jl

Move gcstats inside compile time tracking because compile time tracking allocates in the event of type instability due to tuple construction used to pass results out of the try-catch block.
Fixes #128

Eliminate reported fractional allocations in the case of nonconstant global access

---

src/benchmarking.jl
test/runtests.jl

In its current form, this adds an unacceptable amount of duplication.
Fixes #107

Tell the compiler about the value of the input to f if it is a type (and test)

---

README.md
docs/Project.toml
docs/src/explanations.md
docs/src/index.md
docs/src/migration.md
docs/src/reference.md
docs/src/tutorial.md
docs/src/why.md
src/Chairmarks.jl
src/public.jl

- **Update docs for chagnes since 1.2.2**
- **Add comparison to README and index.html (under experimental advisory) and demote the Why? link because it's beginning to become self evident**

Update docs for chagnes since 1.2.2

---

.github/workflows/CI.yml
codecov.yml

We should cover everything in one of these two cases.

Only process and upload code coverage results in two configurations.

---

src/macro_tools.jl
test/runtests.jl

Improve error message in the absence of arguments to `@b` and add tests

---

Project.toml

This is a big release. It also includes some technically breaking changes.
The biggest breaking change is adding comparative bench-marking which changes parsing syntax for cases where f is a comma separated list already.
For example,
```julia
@b rand(),rand()
```
Used to expand to
```julia
:((Chairmarks.benchmark)((()->(rand(), rand())); ))
```
and now expands to
```julia
:((Chairmarks.benchmark)(((()->rand()), (()->rand())); ))
```
which returns an `NTuple{2, Benchmark}` instead of a `Benchmark`.
Practically, I think this will not adversely impact folks and if it does, it would be perfectly fine to revert it in 1.3.1 and re-release as 2.0.0 because the whole comparative benchmarking scheme is experimental.

Release 1.3.0!

---

src/types.jl
test/runtests.jl

Keep old 9-arg sample constructor and discard checksum

---

README.md

For reasons I don't fully comprehend, as currently written, these links point to an old version of the docs.

fix (?) links to docs in README

---

src/types.jl
test/runtests.jl

`Sample` is already correct by default

Support and test equality and hasing for Benchmark

---

docs/src/migration.md

Since version [v1.6.0](https://github.com/JuliaCI/BenchmarkTools.jl/releases/tag/v1.6.0), BenchmarkTools.jl has [added macros `@btimed` and `@ballocations`](https://github.com/JuliaCI/BenchmarkTools.jl/pull/383). So, the "N/A" is no longer valid in the docs. I wish this change could be reflected in the docs here, too. Thank you in advance!

Mention `@ballocations` of BenchmarkTools.jl in migration.md

---

docs/src/explanations.md

Because @willow-ahrens fixed this leak in a non-breaking release of BenchmarkTools so it was apparently not unavoidable. (https://github.com/JuliaCI/BenchmarkTools.jl/pull/385)

Stop saying that we avoid a memory leak
